### ISSUE TITLE
Allow candidates names to be changed.

### ISSUE THREAD

**Issue by JTWWilson** [Danyc0/CSS-voting-bot#12] opened 2021-04-18 20:23 UTC
Both for general satisfaction and from an inclusivity point of view, we should allow candidates' names to be changed. This could either be through a committee action or the candidates themselves

**Comment by Danyc0** [comment] 2021-04-18 20:37
The problem is that on an on-demand basis, the names are scraped from the guild website. I really didn't want any caching of members, because then there will be inevitable issues with people registering at the last minute.

I'll have a think, but it'll probably involve having a lookup/replace in get_members() into a dict (which would need to be cached to a file) of {<guild name>:<preferred name>}. Then some command in order to set the preferred name. From an inclusivity point of view, being done by the candidate would be best, but from a moderation point of view a committee member doing it would be best. Therefore it might be that two commands are needed, one for a candidate to change it, and one for a committee member to undo the change (in case it's inappropriate).

**Closed** 2021-04-20 12:29 UTC
